const manifest = [
  // {
  //   id: 'hi',
  //   name: 'Hero Icons',
  //   site: 'https://heroicons.com/',
  //   repo: 'https://github.com/tailwindlabs/heroicons',
  //   branch: 'master',
  //   license: 'https://github.com/tailwindlabs/heroicons/blob/master/LICENSE',
  //   path: 'heroicons/optimized',
  // },
  // {
  //   id: 'ri',
  //   name: 'Remix Icon',
  //   site: 'https://remixicon.com/',
  //   repo: 'https://github.com/Remix-Design/RemixIcon',
  //   branch: 'master',
  //   license: 'https://github.com/Remix-Design/RemixIcon/blob/master/License',
  //   path: 'remixicon/icons',
  // },
  // {
  //   id: 'oc',
  //   name: 'Octicons',
  //   site: 'https://primer.style/octicons/',
  //   repo: 'https://github.com/rttll/octicons',
  //   license: 'https://github.com/primer/octicons/blob/main/LICENSE',
  //   path: 'octicons/icons',
  //   excludeFile: new RegExp(/16/, 'g'),
  //   stripFilename: new RegExp(/24/, 'g'),
  // },
  {
    id: 'io',
    name: 'Ionic Icons',
    site: 'https://ionic.io/ionicons',
    repo: 'https://github.com/ionic-team/ionicons',
    license: 'https://github.com/ionic-team/ionicons/blob/master/LICENSE',
    path: 'ionicons/src/svg',
  },
  {
    id: 'bx',
    name: 'Box Icons',
    site: 'https://boxicons.com/',
    license: 'https://github.com/atisawd/boxicons',
    path: 'boxicons/svg',
    stripFilename: new RegExp(/^bx/),
    repo: 'https://github.com/atisawd/boxicons',
  },
  {
    id: 'ti',
    name: 'Tabler Icons',
    site: 'https://tabler-icons.io/',
    license: 'https://github.com/tabler/tabler-icons/blob/master/LICENSE',
    path: '@tabler/icons/icons',
    repo: 'https://github.com/tabler/tabler-icons',
  },
  {
    id: 'in',
    name: 'Iconoir',
    site: 'https://iconoir.com/',
    repo: 'https://github.com/iconoir-icons/iconoir',
    license: 'https://github.com/lucaburgio/iconoir/blob/master/LICENSE',
    path: 'iconoir/icons',
  },
];

export default manifest;
